In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# Q3. Singular Value Decomposition (SVD):
Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print matrices U, Σ, and 𝑉 ் . Verify that A equals the product of U, Σ, and 𝑉 ் . Additionally, find the rank 2 and rank 3 approximations of matrix A.

In [2]:
A = np.random.randint(0, 10, size=(5, 5))
print("Original matrix A:")
print(A)

Original matrix A:
[[5 4 4 9 1]
 [0 2 4 9 3]
 [0 2 8 0 6]
 [1 1 3 8 2]
 [9 2 9 0 1]]


In [3]:
#Q 3
 # Perform Singular Value Decomposition (SVD)
U, Sigma, V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T)

Matrix U:
[[-0.54604812 -0.24657134  0.39198127  0.67877134 -0.16326106]
 [-0.45502894 -0.41559065 -0.23549958 -0.20727933  0.722363  ]
 [-0.34484081  0.36829032 -0.79772651  0.27198468 -0.18736008]
 [-0.38749193 -0.36019218 -0.04473969 -0.56799292 -0.62888313]
 [-0.47509465  0.70789182  0.39053989 -0.31577384  0.14470563]]

Matrix Sigma:
[[20.09397856  0.          0.          0.          0.        ]
 [ 0.         11.52022243  0.          0.          0.        ]
 [ 0.          0.          7.7022812   0.          0.        ]
 [ 0.          0.          0.          1.75698766  0.        ]
 [ 0.          0.          0.          0.          0.32304694]]

Matrix V:
[[-0.36795025  0.41474698  0.70498927 -0.00916387 -0.442158  ]
 [-0.25488298 -0.00219567  0.03087565  0.93623621  0.23987142]
 [-0.60721486  0.48507088 -0.30838207 -0.2755272   0.47432227]
 [-0.60264964 -0.76743269  0.13637748 -0.17104003  0.00263875]
 [-0.26028983  0.06110178 -0.62316811  0.13493648 -0.72247451]]


In [4]:
# Now we show that A equals the product of U, Sigma, and V
A_reconstructed = np.dot(U, np.dot(Sigma_mat, V_transpose))
print("\nVerification that A equals the product of U, Sigma, and V:")
print(np.allclose(A, A_reconstructed))


Verification that A equals the product of U, Sigma, and V:
True
